In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('../data/processed/Fitbit_cleaned.csv')

In [12]:
df.columns

Index(['Age', 'Gender', 'Weight_kg', 'Height_m', 'Max_BPM', 'Avg_BPM',
       'Resting_BPM', 'Session_Duration_hours', 'Workout_Type',
       'Fat_Percentage', 'Water_Intake_liters',
       'Workout_Frequency_days_per_week', 'Experience_Level', 'BMI',
       'Base_MET', 'HR_Intensity', 'Effective_MET', 'Calories_Burned_kcal'],
      dtype='object')

In [3]:
df.shape

(14102, 18)

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14102 entries, 0 to 14101
Data columns (total 18 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   Age                              14102 non-null  int64
 1   Gender                           14102 non-null  object
 2   Weight_kg                        14102 non-null  float64
 3   Height_m                         14102 non-null  float64
 4   Max_BPM                          14102 non-null  int64
 5   Avg_BPM                          14102 non-null  int64
 6   Resting_BPM                      14102 non-null  int64
 7   Session_Duration_hours           14102 non-null  float64
 8   Workout_Type                     14102 non-null  object
 9   Fat_Percentage                   14102 non-null  float64
 10  Water_Intake_liters              14102 non-null  float64
 11  Workout_Frequency_days_per_week  14102 non-null  int64
 12  Experience_Level                 14102 non-null  int64
 13  BMI                              14102 non-null  float64
 14  Base_MET                         14102 non-null  float64
 15  HR_Intensity                     14102 non-null  float64
 16  Effective_MET                    14102 non-null  float64
 17  Calories_Burned_kcal             14102 non-null  float64
dtypes: float64(10), int64(6), object(2)
memory usage: 1.9+ MB

In [5]:
df.columns.tolist()

['Age',
 'Gender',
 'Weight_kg',
 'Height_m',
 'Max_BPM',
 'Avg_BPM',
 'Resting_BPM',
 'Session_Duration_hours',
 'Workout_Type',
 'Fat_Percentage',
 'Water_Intake_liters',
 'Workout_Frequency_days_per_week',
 'Experience_Level',
 'BMI',
 'Base_MET',
 'HR_Intensity',
 'Effective_MET',
 'Calories_Burned_kcal']

In [6]:
df.head()

,Age,Gender,Weight_kg,Height_m,Max_BPM,Avg_BPM,Resting_BPM,Session_Duration_hours,Workout_Type,Fat_Percentage,Water_Intake_liters,Workout_Frequency_days_per_week,Experience_Level,BMI,Base_MET,HR_Intensity,Effective_MET,Calories_Burned_kcal
0,56,Female,53.8,1.62,163,149,71,1.01,HIIT,22.1,3.5,3,1,20.4,9.5,0.847826,8.054348,437.7
1,46,Male,54.9,1.75,170,126,73,0.25,Yoga,19.9,3.4,3,0,18.0,3.0,0.546392,1.639175,22.5
2,32,Female,68.5,1.61,190,171,60,0.33,HIIT,20.4,2.7,3,1,26.5,9.5,0.853846,8.111538,183.4
3,25,Male,98.8,1.86,189,135,69,0.78,Yoga,30.3,4.4,3,0,28.5,3.0,0.550000,1.650000,127.2
4,38,Male,95.5,1.71,176,138,66,0.55,Cardio,23.7,2.2,2,0,32.5,7.0,0.654545,4.581818,240.7

In [11]:
fe_df = df.copy()

In [13]:
X = fe_df.drop('Calories_Burned_kcal', axis=1)
y = fe_df['Calories_Burned_kcal']

In [14]:
fe_df['Fat_Category'] = pd.cut(
    fe_df['Fat_Percentage'],
    bins=[-float('inf'), 7.99, 14.99, 19.99, 24.99, 29.99, float('inf')],
    labels=[
        'Extremely Lean / Very Low',
        'Athletic / Very Fit',
        'Fit',
        'Average',
        'High',
        'Very High'
    ]
)

In [15]:
fe_df['Fat_Category'].value_counts()

Fat_Category
Average                      4412
Fit                          3326
High                         3257
Athletic / Very Fit          1894
Very High                    1213
Extremely Lean / Very Low       0
Name: count, dtype: int64

In [16]:
fe_df[['Fat_Percentage', 'Fat_Category']].head(20)

    Fat_Percentage         Fat_Category
0             22.1              Average
1             19.9                  Fit
2             20.4              Average
3             30.3            Very High
4             23.7              Average
5             28.7                 High
6             25.5                 High
7             18.3                  Fit
8             26.5                 High
9             21.3              Average
10            14.5  Athletic / Very Fit
11            28.7                 High
12            27.6                 High
13            20.9              Average
14            37.7            Very High
15            27.0                 High
16            25.5                 High
17            28.3                 High
18             9.0  Athletic / Very Fit
19            24.7              Average

In [17]:
fe_df['Fat_Category'].isnull().sum()

np.int64(0)

In [18]:
fe_df['BMI_Category'] = pd.cut(
    fe_df['BMI'],
    bins=[-float('inf'), 18.49, 24.99, 29.99, float('inf')],
    labels=[
        'Underweight',
        'Normal',
        'Overweight',
        'Obesity'
    ]
)

In [19]:
fe_df[['BMI', 'BMI_Category']].head(20)

     BMI BMI_Category
0   20.4       Normal
1   18.0  Underweight
2   26.5   Overweight
3   28.5   Overweight
4   32.5      Obesity
5   18.1  Underweight
6   27.1   Overweight
7   27.3   Overweight
8   21.7       Normal
9   20.3       Normal
10  19.7       Normal
11  21.9       Normal
12  24.8       Normal
13  29.4   Overweight
14  28.4   Overweight
15  18.0  Underweight
16  20.8       Normal
17  29.2   Overweight
18  21.1       Normal
19  23.8       Normal

In [20]:
fe_df['Weekly_Workout_Hours'] = (
    fe_df['Session_Duration_hours']
    * fe_df['Workout_Frequency_days_per_week']
)

In [21]:
fe_df[
    [
        'Session_Duration_hours',
        'Workout_Frequency_days_per_week',
        'Weekly_Workout_Hours'
    ]
].head(10)

,Session_Duration_hours,Workout_Frequency_days_per_week,Weekly_Workout_Hours
0,1.01,3,3.03
1,0.25,3,0.75
2,0.33,3,0.99
3,0.78,3,2.34
4,0.55,2,1.10
5,0.75,5,3.75
6,0.41,2,0.82
7,0.52,3,1.56
8,0.78,2,1.56
9,0.67,4,2.68

In [25]:
fe_df.shape

(14102, 21)

In [24]:
fe_df.columns

Index(['Age', 'Gender', 'Weight_kg', 'Height_m', 'Max_BPM', 'Avg_BPM',
       'Resting_BPM', 'Session_Duration_hours', 'Workout_Type',
       'Fat_Percentage', 'Water_Intake_liters',
       'Workout_Frequency_days_per_week', 'Experience_Level', 'BMI',
       'Base_MET', 'HR_Intensity', 'Effective_MET', 'Calories_Burned_kcal',
       'Fat_Category', 'BMI_Category', 'Weekly_Workout_Hours'],
      dtype='object')

In [27]:
fe_df.to_csv(
    '../data/processed/Fitbit_feature_engineered.csv',
    index=False
)